name: pygms
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.*
    - pip
    - numpy
    - scipy
    - matplotlib
    - pandas
    - ipython
    - nb_conda_kernels
    - cython
    - flake8
    - pydocstyle
    - pep8
    - sphinx
    - sphinxcontrib-bibtex
    - sphinx_rtd_theme
    - doc8
    - m2r
    - coverage
