name: pyGMS
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.*
    - pip
    - numpy
    - scipy
    - matplotlib
    - pandas
    - ipython
    - cython
    - flake8
    - pydocstyle
