name: pygms
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.*
    - pip
    - numpy
    - scipy
    - matplotlib
    - pandas
    - ipython
    - nb_conda_kernels
    - cython
    - flake8
    - pydocstyle
    - pep8
    - sphinx
    - sphinxcontrib-bibtex
    - doc8
    - m2r
    - pip:
        - sphinx_theme
        - sphinxcontrib-jupyter
